export enum EUserRole {
    ANAGRAFICHE_SPI = 'ROLE_GEPA-ANAGRAFICHE_INGROSSO',
    ANAGRAFICHE_VISUALIZZATORE = 'ROLE_GEPA-ANAGRAFICHE_MONITOR',
    ANAGRAFICHE_BIL = 'ROLE_GEPA-ANAGRAFICHE_BILANCIO',
    ANAGRAFICHE_DET = 'ROLE_GEPA-ANAGRAFICHE_DETTAGLIO',
    CORE_TAV_OP1 = "ROLE_GEPA-CORE_TVOP1",
    CORE_TAV_OP2 = "ROLE_GEPA-CORE_TVOP2",
    CORE_OPERATOR = "ROLE_GEPA-CORE_OPER",
    CORE_VALID = "ROLE_GEPA-CORE_VALID"
}

